with
    accounts as (select id, country_code from input.accounts where name is not null and country_code in ({country_code})),

    video_impression_info as (select account_id, json_extract_scalar(data, '$.placement') as placement, json_extract_scalar(meta_tag, '$.recall_bucket') as bucket, json_extract_array(meta_tag, '$.recall_strategy') as strategies, extract(date from created_at) as date from (select *, json_extract_scalar(data, '$.meta_tag') as meta_tag from stream_events.video_impression where created_at >= '{start_time}' and created_at < '{end_time}') where json_extract_scalar(meta_tag, '$.recall_bucket') is not null and json_extract_scalar(meta_tag, '$.recall_bucket') != '' and json_extract_scalar(data, '$.placement') not like 'immersive%'),

    video_impression_one_day_info as (select account_id, json_extract_scalar(data, '$.placement') as placement, json_extract_scalar(meta_tag, '$.recall_bucket') as bucket, json_extract_array(meta_tag, '$.recall_strategy') as strategies, extract(date from created_at) as date from (select *, json_extract_scalar(data, '$.meta_tag') as meta_tag from stream_events.video_impression where created_at >= timestamp_sub(timestamp'{start_time}', interval 1 day) and created_at < timestamp_sub(timestamp'{end_time}', interval 1 day)) where json_extract_scalar(meta_tag, '$.recall_bucket') is not null and json_extract_scalar(meta_tag, '$.recall_bucket') != '' and json_extract_scalar(data, '$.placement') not like 'immersive%'),

    video_impression_three_day_info as (select account_id, json_extract_scalar(data, '$.placement') as placement, json_extract_scalar(meta_tag, '$.recall_bucket') as bucket, json_extract_array(meta_tag, '$.recall_strategy') as strategies, extract(date from created_at) as date from (select *, json_extract_scalar(data, '$.meta_tag') as meta_tag from stream_events.video_impression where created_at >= timestamp_sub(timestamp'{start_time}', interval 3 day) and created_at < timestamp_sub(timestamp'{end_time}', interval 3 day)) where json_extract_scalar(meta_tag, '$.recall_bucket') is not null and json_extract_scalar(meta_tag, '$.recall_bucket') != '' and json_extract_scalar(data, '$.placement') not like 'immersive%'),

    video_impression_seven_day_info as (select account_id, json_extract_scalar(data, '$.placement') as placement, json_extract_scalar(meta_tag, '$.recall_bucket') as bucket, json_extract_array(meta_tag, '$.recall_strategy') as strategies, extract(date from created_at) as date from (select *, json_extract_scalar(data, '$.meta_tag') as meta_tag from stream_events.video_impression where created_at >= timestamp_sub(timestamp'{start_time}', interval 7 day) and created_at < timestamp_sub(timestamp'{end_time}', interval 7 day)) where json_extract_scalar(meta_tag, '$.recall_bucket') is not null and json_extract_scalar(meta_tag, '$.recall_bucket') != '' and json_extract_scalar(data, '$.placement') not like 'immersive%'),

    video_impression_fourteen_day_info as (select account_id, json_extract_scalar(data, '$.placement') as placement, json_extract_scalar(meta_tag, '$.recall_bucket') as bucket, json_extract_array(meta_tag, '$.recall_strategy') as strategies, extract(date from created_at) as date from (select *, json_extract_scalar(data, '$.meta_tag') as meta_tag from stream_events.video_impression where created_at >= timestamp_sub(timestamp'{start_time}', interval 14 day) and created_at < timestamp_sub(timestamp'{end_time}', interval 14 day)) where json_extract_scalar(meta_tag, '$.recall_bucket') is not null and json_extract_scalar(meta_tag, '$.recall_bucket') != '' and json_extract_scalar(data, '$.placement') not like 'immersive%'),

    video_impression_thirty_day_info as (select account_id, json_extract_scalar(data, '$.placement') as placement, json_extract_scalar(meta_tag, '$.recall_bucket') as bucket, json_extract_array(meta_tag, '$.recall_strategy') as strategies, extract(date from created_at) as date from (select *, json_extract_scalar(data, '$.meta_tag') as meta_tag from stream_events.video_impression where created_at >= timestamp_sub(timestamp'{start_time}', interval 30 day) and created_at < timestamp_sub(timestamp'{end_time}', interval 30 day)) where json_extract_scalar(meta_tag, '$.recall_bucket') is not null and json_extract_scalar(meta_tag, '$.recall_bucket') != '' and json_extract_scalar(data, '$.placement') not like 'immersive%'),

    video_impression_all_info as (select * from video_impression_info union all select * from video_impression_one_day_info union all select * from video_impression_three_day_info union all select * from video_impression_seven_day_info union all select * from video_impression_fourteen_day_info union all select * from video_impression_thirty_day_info),

    video_impression_all as (select account_id, placement, bucket, replace(strategy, '"', '') as strategy, date from video_impression_all_info as v cross join unnest(v.strategies) as strategy),

    accounts_video_impression_all_info as (select distinct country_code, account_id, placement, bucket, strategy, date from video_impression_all inner join accounts on account_id = id),

    retention_day_event as (select * from accounts_video_impression_all_info where date = extract(date from timestamp'{start_time}')),

    initial_event as (select country_code, account_id, placement, bucket, strategy, date as initial_date from accounts_video_impression_all_info where date != extract(date from timestamp'{start_time}')),

    retention_event as (select r.country_code as country_code, r.account_id as account_id, r.placement as placement, r.bucket as bucket, r.strategy as strategy, initial_date, r.date as retention_date, date_diff(r.date, initial_date, day) as date_diff from retention_day_event as r inner join initial_event as i on r.country_code = i.country_code and r.account_id = i.account_id and r.placement = i.placement and r.bucket = i.bucket and r.strategy = i.strategy),

    initial_count as (select country_code, placement, bucket, strategy, initial_date, count(distinct account_id) as initial_num from initial_event group by country_code, placement, bucket, strategy, initial_date),

    retention_count as (select country_code, placement, bucket, strategy, initial_date, retention_date, date_diff, count(distinct account_id) as retention_num from retention_event group by country_code, placement, bucket, strategy, initial_date, retention_date, date_diff)

    select i.country_code as country_code, i.placement as placement, i.initial_date as initial_date, retention_date, date_diff, i.bucket as bucket, i.strategy as strategy, initial_num, ifnull(retention_num, 0) as retention_num, round(ifnull(retention_num, 0)/initial_num, 4) as retention_rate from initial_count as i left join retention_count as r on i.country_code = r.country_code and i.placement = r.placement and i.bucket = r.bucket and i.strategy = r.strategy and i.initial_date = r.initial_date where retention_date is not null and date_diff is not null order by country_code, placement, bucket, strategy, initial_date, date_diff